export const auth = {
  login: {
    title: "Bienvenido de Nuevo",
    subtitle: "Inicia sesión en tu cuenta para continuar",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "tu@correo.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Ingresa tu contraseña",
    rememberMe: "Recuérdame",
    forgotPassword: "¿Olvidaste tu contraseña?",
    submitButton: "Iniciar Sesión",
    submittingButton: "Iniciando sesión...",
    googleButton: "Continuar con Google",
    noAccount: "¿No tienes una cuenta?",
    signUpLink: "Regístrate",
    successMessage: "¡Bienvenido de nuevo!",
  },

  register: {
    title: "Crear Cuenta",
    subtitle: "Únete a nosotros y comienza a comprar",
    firstNameLabel: "Nombre",
    firstNamePlaceholder: "Juan",
    lastNameLabel: "Apellido",
    lastNamePlaceholder: "Pérez",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "tu@correo.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Crea una contraseña segura",
    confirmPasswordLabel: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Reingresa tu contraseña",
    termsLabel: "Acepto los Términos y Condiciones y la Política de Privacidad",
    submitButton: "Crear Cuenta",
    submittingButton: "Creando cuenta...",
    googleButton: "Regístrate con Google",
    haveAccount: "¿Ya tienes una cuenta?",
    signInLink: "Iniciar sesión",
    successMessage: "¡Cuenta creada exitosamente!",
  },

  resetPassword: {
    title: "Restablecer Contraseña",
    subtitle: "Ingresa tu correo para recibir un código de restablecimiento",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "tu@correo.com",
    submitButton: "Enviar Código",
    submittingButton: "Enviando...",
    codeLabel: "Código de Restablecimiento",
    codePlaceholder: "Ingresa el código de 6 dígitos",
    newPasswordLabel: "Nueva Contraseña",
    newPasswordPlaceholder: "Ingresa la nueva contraseña",
    confirmButton: "Restablecer Contraseña",
    confirmingButton: "Restableciendo...",
    successMessage: "¡Contraseña restablecida exitosamente!",
    backToLogin: "Volver al inicio de sesión",
    codeExpiry: "El código expira en 15 minutos",
  },

  errors: {
    INVALID_CREDENTIALS: "Correo o contraseña inválidos",
    EMAIL_ALREADY_EXISTS: "Ya existe una cuenta con este correo",
    INVALID_TOKEN: "Código de restablecimiento inválido o expirado",
    WEAK_PASSWORD: "La contraseña debe tener al menos 8 caracteres con mayúsculas, minúsculas y números",
    TERMS_NOT_ACCEPTED: "Debes aceptar los términos y condiciones",
    PASSWORDS_DONT_MATCH: "Las contraseñas no coinciden",
  },

  validation: {
    emailRequired: "El correo es requerido",
    emailInvalid: "Por favor ingresa un correo válido",
    passwordRequired: "La contraseña es requerida",
    passwordMin: "La contraseña debe tener al menos 8 caracteres",
    passwordStrength: "La contraseña debe contener mayúsculas, minúsculas y números",
    firstNameRequired: "El nombre es requerido",
    lastNameRequired: "El apellido es requerido",
    termsRequired: "Debes aceptar los términos y condiciones",
  },
};
